'use strict';

export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const TOGGLE_REMINDER = 'TOGGLE_REMINDER';
export const EDIT_REMINDER = 'EDIT_REMINDER';
export const REMINDERS_UNDO = 'REMINDERS_UNDO';
export const REMINDERS_REDO = 'REMINDERS_REDO';

export const ADD_FAV_LOCATION = 'ADD_FAV_LOCATION';
export const EDIT_FAV_LOCATION = 'EDIT_FAV_LOCATION';
export const DELETE_FAV_LOCATION = 'DELETE_FAV_LOCATION';
export const FAV_LOCATIONS_UNDO = 'FAV_LOCATIONS_UNDO';
export const FAV_LOCATIONS_REDO = 'FAV_LOCATIONS_REDO';

export const LOAD_DATA = "LOAD_DATA";
export const DATA_LOADED = "DATA_LOADED";

export const SAVE_DATA = "SAVE_DATA";
export const DATA_SAVED = "DATA_SAVED";

export const DISPLAY_VIEW = "DISPLAY_VIEW";
